# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e60cdf3ee44a451b5e4dbf08f62b18cbde6bf12d3809461595c8fa3da99387359e5fb0ffaaa9ccb69234f491b113e68ada319db94ba926da6bda6f7e342527d

test:
  secret_key_base: e5991eedf88f10d6f9420a8395926f27eb6e5298b075f69151f675a847144c72ca49e2022d467e45aa6ef314149735af31cc2cd1875ca0bca95074799d5add2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
